# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "rtsx_usb_sdmmc" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" "amdgpu" ];
  boot.extraModulePackages = [ ];
  boot.kernelPackages = pkgs.linuxPackages_latest;
  boot.kernel.sysctl = {
    "kernel.unprivileged_userns_clone" = 1;
  };

  boot.initrd.luks.devices."luks" = {
    device = "/dev/disk/by-uuid/64bae9a2-99bb-41ce-ab62-52d8d8717846";
    allowDiscards = true;
    preLVM = true;
  };

  fileSystems."/" =
    { device = "/dev/mapper/lvm-root";
      fsType = "xfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/587B-DE40";
      fsType = "vfat";
    };

  fileSystems."/home/link/Datos" = {
    encrypted = {
      blkDev = "/dev/disk/by-uuid/c16e4bcf-d97a-40aa-b825-41e041b99d68";
      enable = true;
      keyFile = "/mnt-root/.keyfile";
      label = "encrypteddata";
    };
    device = "/dev/mapper/encrypteddata";
    fsType = "xfs";
  };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/cab84cbb-5c33-4449-b8a2-d1980134f73a"; }
    ];

  nix.maxJobs = lib.mkDefault 8;
}
