# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "rtsx_usb_sdmmc" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.kernelParams = [ "intel_idle.max_cstate=1" ];
  boot.kernelPackages = pkgs.linuxPackages_latest;
  boot.kernel.sysctl = {
    "kernel.unprivileged_userns_clone" = 1;
    "dev.i915.perf_stream_paranoid" = 0; 
  };

  boot.initrd.luks.fido2Support = true;

  boot.initrd.luks.devices."luks" = {
    device = "/dev/disk/by-uuid/UUIDchangeme";
    allowDiscards = true;
    preLVM = true;
    fido2.credential = "fidochangeme";
  };

  fileSystems."/" =
    { device = "/dev/mapper/lvm-root";
      fsType = "btrfs";
    };

  fileSystems."/home" =
    { device = "/dev/mapper/lvm-home";
      fsType = "btrfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/bootChangeme";
      fsType = "vfat";
    };

  fileSystems."/home/link/Datos" = {
    encrypted = {
      blkDev = "/dev/disk/by-uuid/dataDiskChangeme";
      enable = true;
      keyFile = "/mnt-root/.keyfile";
      label = "encrypteddata";
    };
    device = "/dev/mapper/encrypteddata";
    fsType = "ext4";
  };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/swapChangeme"; }
    ];

  nix.maxJobs = lib.mkDefault 12;
}
