#!/bin/bash

# Set hostname
hostnamectl set-hostname link-gp76

# Add rpmfusion repos
rpm-ostree install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

# Add COPR repos
curl -L "https://copr.fedorainfracloud.org/coprs/hyperreal/better_fonts/repo/fedora-36/hyperreal-better_fonts-fedora-36.repo" > /etc/yum.repos.d/better-fonts.repo
curl -L "https://copr.fedorainfracloud.org/coprs/sunwire/input-remapper/repo/fedora-36/sunwire-input-remapper-fedora-36.repo" > /etc/yum.repos.d/input-remapper.repo

# Add VSCode repo
rpm --import https://packages.microsoft.com/keys/microsoft.asc
echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo

# First package installation
rpm-ostree install python3-input-remapper vim zsh zsh-syntax-highlighting papirus-icon-theme zsh-autosuggestions google-noto-cjk-fonts google-noto-emoji-fonts nodejs npm python-neovim webp-pixbuf-loader java-11-openjdk-devel neofetch alsa-plugins-pulseaudio.x86_64 alsa-lib-devel.x86_64 yt-dlp p7zip fontconfig-font-replacements fontconfig-enhanced-defaults hunspell-ca hunspell-es-ES mythes-ca mythes-es mythes-en hyphen-es hyphen-ca hyphen-en aspell-ca aspell-es aspell-en android-tools piper redhat-lsb-core solaar zpaq lm_sensors strawberry code

# Install computer specific packages
rpm-ostree install pam-u2f pamu2fcfg

# Adding flathub repo
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

# Installing flatpak applications
flatpak install -y flathub sh.ppy.osu com.google.Chrome com.discordapp.Discord org.telegram.desktop com.valvesoftware.Steam org.DolphinEmu.dolphin-emu net.lutris.Lutris net.pcsx2.PCSX2 org.telegram.desktop org.qbittorrent.qBittorrent org.jdownloader.JDownloader org.gnome.Boxes com.nextcloud.desktopclient.nextcloud org.desmume.DeSmuME org.nicotine_plus.Nicotine com.github.AmatCoder.mednaffe com.obsproject.Studio org.gimp.GIMP com.heroicgameslauncher.hgl org.kde.palapeli org.kde.kpat org.gtk.Gtk3theme.Breeze
