# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "rtsx_usb_sdmmc" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.kernelPackages = pkgs.linuxPackages_latest;
  boot.kernel.sysctl = {
    "kernel.unprivileged_userns_clone" = 1;
    "fs.inotify.max_user_watches" = 524288;
  };

  boot.initrd.luks.fido2Support = true;

  boot.initrd.luks.devices."luks" = {
    device = "/dev/disk/by-uuid/UUIDchangeme";
    allowDiscards = true;
    preLVM = true;
    fido2.credential = "fidochangeme";
  };

  fileSystems."/" =
    { device = "/dev/mapper/lvm-root";
      fsType = "btrfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/249E-5A45";
      fsType = "vfat";
    };

  fileSystems."/home/link/Datos" = {
    encrypted = {
      blkDev = "/dev/disk/by-uuid/cfcf44a7-2604-4df4-b744-f45fae368686";
      enable = true;
      keyFile = "/mnt-root/.keyfile";
      label = "encrypteddata";
    };
    device = "/dev/mapper/encrypteddata";
    fsType = "btrfs";
  };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/37cbbf94-781f-4197-8af9-d4fa6fa2c6e3"; }
    ];

  nix.maxJobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
