# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "rtsx_usb_sdmmc" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" "amdgpu" ];
  boot.extraModulePackages = [ ];
  boot.kernelPackages = pkgs.linuxPackages_latest;
  boot.kernel.sysctl = {
    "kernel.unprivileged_userns_clone" = 1;
  };

  boot.initrd.luks.devices."luks" = {
    device = "/dev/disk/by-uuid/UUIDchangeme";
    allowDiscards = true;
    preLVM = true;
  };

  fileSystems."/" =
    { device = "/dev/mapper/lvm-root";
      fsType = "xfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/bootChangeme";
      fsType = "vfat";
    };

  fileSystems."/home/link/Datos" = {
    encrypted = {
      blkDev = "/dev/disk/by-uuid/dataDiskChangeme";
      enable = true;
      keyFile = "/mnt-root/.keyfile";
      label = "encrypteddata";
    };
    device = "/dev/mapper/encrypteddata";
    fsType = "btrfs";
  };

  fileSystems."/home/link/Torrent" = {
    encrypted = {
      blkDev = "/dev/disk/by-uuid/torrentDiskChangeme";
      enable = true;
      keyFile = "/mnt-root/.torrentkey";
      label = "torrent";
    };
    device = "/dev/mapper/torrent";
    fsType = "btrfs";
  };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/swapChangeme"; }
    ];

  nix.maxJobs = lib.mkDefault 12;
}
