# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "rtsx_usb_sdmmc" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.kernelPackages = pkgs.linuxKernel.packages.linux_xanmod_latest;
  boot.kernel.sysctl = {
    "kernel.unprivileged_userns_clone" = 1;
    "dev.i915.perf_stream_paranoid" = 0;
  };

  boot.kernelParams = [
    "mem_sleep_default=deep"
    "module_blacklist=i915"
  ];

  boot.resumeDevice = "/dev/disk/by-uuid/swapChangeme";

  boot.initrd.luks.devices."luks" = {
    device = "/dev/disk/by-uuid/UUIDchangeme";
    allowDiscards = true;
    preLVM = true;
  };

  fileSystems."/" =
    { device = "/dev/mapper/lvm-root";
      fsType = "btrfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/bootChangeme";
      fsType = "vfat";
    };

  fileSystems."/home/link/Datos" = {
    encrypted = {
      blkDev = "/dev/disk/by-uuid/5e6d074b-663c-45b0-b1dc-6bb121ba9fb1";
      enable = true;
      keyFile = "/mnt-root/.datoskey";
      label = "datos";
    };
    device = "/dev/mapper/datos";
    fsType = "btrfs";
    options = [
      "defaults"
      "noatime"
      "autodefrag"
      "compress=zstd"
    ];
  };

  fileSystems."/home/link/Torrent" = {
    encrypted = {
      blkDev = "/dev/disk/by-uuid/e3839618-a2ea-4043-9359-9906c76eee0e";
      enable = true;
      keyFile = "/mnt-root/.torrentkey";
      label = "torrent";
    };
    device = "/dev/mapper/torrent";
    fsType = "btrfs";
    options = [
      "defaults"
      "noatime"
      "autodefrag"
      "compress=zstd"
    ];
  };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/swapChangeme"; }
    ];

  nix.settings.max-jobs = lib.mkDefault 14;
}
