# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "rtsx_usb_sdmmc" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.kernelParams = [ "intel_idle.max_cstate=1" ];
  boot.kernelPackages = pkgs.linuxPackages_latest;
  boot.kernel.sysctl = {
    "kernel.unprivileged_userns_clone" = 1;
  };

  boot.initrd.luks.fido2Support = true;

  boot.initrd.luks.devices."luks" = {
    device = "/dev/disk/by-uuid/5aa4bd29-772f-4b7b-bc79-c8f6266ebce8";
    allowDiscards = true;
    preLVM = true;
    fido2.credential = "94d09f843ba8e889a32ec63747262d1d9acb07b8c78dd883844c9b003d0ebee9fd4e52dae2262619c1da2be7562ec9dd94888c71a9326fea70dfe16214b5ea8ec01459010000";
  };

  fileSystems."/" =
    { device = "/dev/mapper/lvm-root";
      fsType = "btrfs";
    };

  fileSystems."/home" =
    { device = "/dev/mapper/lvm-home";
      fsType = "btrfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/249E-5A45";
      fsType = "vfat";
    };

  fileSystems."/home/link/Datos" = {
    encrypted = {
      blkDev = "/dev/disk/by-uuid/20976b67-c796-47c9-90dd-62c1edc34258";
      enable = true;
      keyFile = "/mnt-root/.keyfile";
      label = "encrypteddata";
    };
    device = "/dev/mapper/encrypteddata";
    fsType = "ext4";
  };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/37cbbf94-781f-4197-8af9-d4fa6fa2c6e3"; }
    ];

  nix.maxJobs = lib.mkDefault 12;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
