version: '3'
services:
  DB:
    container_name: 'mariadb'
    image: 'mariadb:latest'
    restart: always
    ports: 
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_HOST: 'database'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
