#!/usr/bin/env bash

if [ "$1" == "-r" ]; then

	SAVEIFS=$IFS
	IFS=$(echo -en "\n\b")

	cd $2

	for file in $(ls $2); do
		zip -r ${file}.zip $file
		mv ${file}.zip ${file}.cbz
	done
	IFS=$SAVEIFS

elif [ "$1" == "-h" ]; then
	echo "Options:"
	echo "makecbz [-r] folder"
	echo "-r to make the contents of the folder a cbz instead of the folder itself"
	echo "Use -h to see this help"
else
	SAVEIFS=$IFS
	IFS=$(echo -en "\n\b")
	count=$(echo "$1" | sed 's/[^/]//g' | wc -m)
	filename=$(echo "$1" | cut -d "/" -f $count)

	cd "$(dirname $1)"
	zip -r "${filename}.zip" "${filename}"
	mv "${filename}.zip" "${filename}.cbz"
	IFS=$SAVEIFS
fi
